[Dropdown] Updated stylings, states and stories
cfpb/design-system-react pull request #176
Opened 2023-09-19 20:06 UTC by shindigira

Closes #173 

## Changes

- [New] Uses the standard CFPB accessibility styling (dotted outline when focused) in the Options 
- [New] Utilizes the proper  CFPB-style 'down' [&#9660;](http://www.fileformat.info/info/unicode/char/25bc/index.htm) icon in the Dropdown
- [New] `error` prop that causes a red border around the Dropdown
- [New] Dropdown Storybook story ('With Error')
- [Update] Utilize the current library's Checkbox instead of a generic checkbox
- [Update] Removed internal useState usage in **_both_** Checkbox and Dropdown. State must come externally in a `controlled` manner.
- [Update] Update the storybook stories of Checkbox and Dropdown to use external state.
- [Update] Update TypeScript settings
- [Update] Update the Multi-Select variation
- [Update] Incorporate the Menu Options styling
- [Update] Incorporate the styling from Figma

## How to test this PR

1. `yarn vitest`
2. See that everything passes
3. `yarn storybook`
4. Test the Checkbox and Dropdown stories
5. Inspect the new styling and compare with the figma and CFPB design

## Screenshots

### Default
<img width="1119" alt="Screenshot 2023-09-19 at 4 01 28 PM" src="https://github.com/cfpb/design-system-react/assets/13324863/eb1572a1-28af-4e42-8bfa-4abbfeaac331">

### Error
<img width="1154" alt="Screenshot 2023-09-19 at 4 01 09 PM" src="https://github.com/cfpb/design-system-react/assets/13324863/f6d47906-6814-44af-8b1a-95306ec60c62">

### Multiselect with Pills and Checkboxes
<img width="1106" alt="Screenshot 2023-09-19 at 4 02 01 PM" src="https://github.com/cfpb/design-system-react/assets/13324863/d400d2c9-486e-4475-81f7-d7386294ee0a">

### Multiselect -- Menu Options (Dotted Outline While Focused)
<img width="1200" alt="Screenshot 2023-09-25 at 9 53 40 AM" src="https://github.com/cfpb/design-system-react/assets/13324863/aa6bb7f2-fa88-422a-b198-f11260b0a07a">

2023-09-19 22:03 UTC, meissadia requested changes
- Should we try to better align stories to what is in the DS?
  - Sigmund has done a great job of demonstrating what is possible with the Dropdown component but a lot of the scenarios are not represented in the DS ("With error", "Disabled", "Multi-select with checkboxes", etc).  I could use some clarification on the source for all of the features that are not outlined in the DS.

2023-09-19 22:03 UTC, meissadia reviewed
- I pushed a commit to update story names to `sentence case`
- I pushed a commit to update `Dropdown` to `Dropdowns`, to align with the way we've been updating the naming of Story pages

2023-09-19 22:06 UTC, meissadia commented
I had also previously added a `Clear All` button to the selected pills section and I'm struggling to find a reference for the source (Not seeing it in the DS or in the Figma).  Should this be removed?

![Screenshot 2023-09-19 at 3 50 17 PM](https://github.com/cfpb/design-system-react/assets/2592907/8108c7e7-7446-407d-b9c1-38060df60720)

2023-09-22 20:52 UTC, meissadia requested changes
Functionality looks great! Could use some code cleanup.
 
- Border for Dropdown -> Error feels a bit heavy.  I think I've seen it mentioned that it should be 2px?
- Still in discussion but we should match the DS multiselect's :focus and :hover styles as closely as possible for now

2023-09-22 20:52 UTC, meissadia commented on src/components/Dropdown/Dropdown.less
> +  // outline: solid #919395 !important;
```suggestion
```

2023-09-22 20:52 UTC, meissadia commented on src/components/Dropdown/Dropdown.less
> +  // outline: solid #d14124 !important;
```suggestion
```

2023-09-22 20:52 UTC, meissadia commented on src/components/Checkbox/Checkbox.stories.tsx
> +  name: 'Default dropdown',
```suggestion
  name: 'Default checkbox',
```

2023-09-22 20:52 UTC, meissadia commented on src/components/Dropdown/Dropdown.less
> +}
Empty selector needed?
```suggestion
```

2023-09-22 20:52 UTC, meissadia commented on src/components/Dropdown/Dropdown.less
> +}
Empty selector needed?
```suggestion
```

2023-09-22 20:52 UTC, meissadia commented on src/components/Dropdown/Dropdown.tsx
> +        // menuIsOpen
Remove unused prop? 
```suggestion
```

2023-09-22 20:52 UTC, meissadia commented on src/components/Dropdown/DropdownInputWithCheckbox.tsx
> +    // outlineOffset: '3px'
```suggestion
```

2023-09-22 20:52 UTC, meissadia commented on src/components/Dropdown/DropdownInputWithCheckbox.tsx
> +  };
Remove style object that is not currently applying any styles?
```suggestion
```

2023-09-22 20:52 UTC, meissadia commented on src/components/Dropdown/DropdownInputWithCheckbox.tsx
> +  console.log('rest:', rest);
```suggestion
```

2023-09-22 20:52 UTC, meissadia commented on src/components/Dropdown/DropdownInputWithCheckbox.tsx
> +      // getStyles={getStyles}
```suggestion
```

2023-09-22 20:52 UTC, meissadia commented on src/components/Dropdown/styles.tsx
> +    // backgroundColor: '#f0f0f0', // Background color of the entire menu
```suggestion
```

2023-09-22 20:52 UTC, meissadia commented on src/components/Checkbox/Checkbox.stories.tsx
> +/* eslint-disable unicorn/prevent-abbreviations */
Necessary? I'm not sure which plugin it is but my VS Code automatically updates names such as `_args` for me upon save.  For consistency, I think this should stay enabled. 
```suggestion
```

2023-09-22 21:01 UTC, natalia-fitzgerald commented
@shindigira 
- For the Multiselect remove the "x" within the input field (and the gray box)
  - We can handle the clear function at the form level
- For the Multiselect use the standard CFPB styling for the focus state
  - Changes to the focus state would be global and affect the rest of our CFPB custom components (this is out of scope for this effort)

There are known bugs in the CFPB Design System - Multiselect component that we should keep in mind as we build out this component. We can then contribute back to the system while we build the React component library. 

**Some known bugs are documented here:** 

https://github.com/cfpb/design-system/issues?q=is%3Aissue+is%3Aopen+multiselect
https://github.cfpb.gov/CFGOV/platform/issues/3291
https://github.cfpb.gov/CFGOV/platform/issues/3283

2023-09-22 21:02 UTC, natalia-fitzgerald reviewed
@shindigira 
- For the Multiselect remove the "x" within the input field (and the gray box)
  - We can handle the clear function at the form level
- For the Multiselect use the standard CFPB styling for the focus state
  - Changes to the focus state would be global and affect the rest of our CFPB custom components (this is out of scope for this effort)

There are known bugs in the CFPB Design System - Multiselect component that we should keep in mind as we build out this component. If we have ideas about how to solve these issues we can contribute back to the system while we build the React component library. 

**Some known bugs are documented here:** 

https://github.com/cfpb/design-system/issues?q=is%3Aissue+is%3Aopen+multiselect
https://github.cfpb.gov/CFGOV/platform/issues/3291
https://github.cfpb.gov/CFGOV/platform/issues/3283
https://github.com/cfpb/design-system/issues/1728

2023-09-26 17:18 UTC, meissadia commented on src/components/Dropdown/Dropdown.less
> +// }
```suggestion
```

2023-09-26 23:32 UTC, meissadia commented on src/components/Dropdown/Dropdown.tsx
> +
Per a convo w/ Natalia, I've pushed a change to clear the background styling

When Dropdown not focused
![Screenshot 2023-09-26 at 5 29 41 PM](https://github.com/cfpb/design-system-react/assets/2592907/0afa528a-6ab0-4bbb-a0b7-8c9065f0f29e)
 
When Dropdown is focused (x is darker)
![Screenshot 2023-09-26 at 5 29 49 PM](https://github.com/cfpb/design-system-react/assets/2592907/6be346b7-9e09-4209-9c0d-401bd3a5faf6)

2023-09-26 23:38 UTC, meissadia commented
I pushed some changes to:
- Fix the Dropdown interactions on the Overview page
- Remove custom styles on the in-field `Clear all` "X"
  - ![Screenshot 2023-09-26 at 5 24 46 PM](https://github.com/cfpb/design-system-react/assets/2592907/5cccaef9-0f2f-4fc5-81c0-7c67c9aa3d57)
- Address some grey border overhang on the Dropdown error state
  - Before / After
  - <img width="913" alt="Screenshot 2023-09-26 at 5 37 04 PM" src="https://github.com/cfpb/design-system-react/assets/2592907/2475531b-b8d1-491e-bd50-c220c72ebc1e">

2023-09-26 23:39 UTC, meissadia approved these changes
@shindigira Please take a look at the adjustments I made to confirm you're okay with them

2023-09-27 15:32 UTC, merged