Verify well component
cfpb/design-system-react pull request #212
Opened 2023-10-23 18:37 UTC by meissadia

Part of SBL Project # 45

## Changes

- Add unit tests
- Add DS intro paragraph
- Sync story content with DS

## How to test this PR

1. yarn vitest Well

## Screenshots
![Screenshot 2023-10-23 at 12 36 21 PM](https://github.com/cfpb/design-system-react/assets/2592907/92fec41f-50bd-43cd-a1c4-b7410a3df936)

2023-10-26 02:03 UTC, billhimmelsbach requested changes
Heyo! 2 small comments and 1 change requested. 👍

2023-10-26 02:51 UTC, meissadia commented on src/components/Well/Well.stories.tsx
> +};
I'm all for a linting rule that applies it as it's certainly not something I would want to watch for.  Candidly I didn't even know what was a "thing" 😬

2023-10-26 02:52 UTC, meissadia commented on src/components/Well/Well.tsx
> + * Wells are used to highlight specific information within a designated section of a page. This breaks up the flow of content on the page and helps to emphasize and set apart the content that is incl
Careless oversight on my part, thanks for being diligent!

2023-10-26 02:59 UTC, billhimmelsbach commented on src/components/Well/Well.stories.tsx
> +};
It's super hard to even catch, so linters to the rescue! 🦸‍♂️

2023-10-26 03:06 UTC, meissadia commented
@billhimmelsbach @natalia-fitzgerald I'd like to have a quick chat about this component when possible. I think that this implementation may be an incorrect interpretation of what constitutes a `Well`.  
 
From our `Complete user profile` prototype talks/explorations it seems that the `Well` is actually the grey box w/ border & padding that could house *any* content. 

The [DS example](https://cfpb.github.io/design-system/patterns/wells#well) demonstrates usage with a Text Introduction-like set of elements but I don't think that content is part of the `Well`.

2023-10-26 03:56 UTC, natalia-fitzgerald commented
Here's my thinking (we can discuss more tomorrow): 
- Add the actual well to the DS components section (`o-well` in other words the gray box with padding)
- Add this well component (gray box with padding) to the the DSR
- Propose a name change to the well pattern in the CFPB DS. 
- Add the newly named well pattern thingy to our component library (o-well + heading + body/paragraph + link (optional)

The catch about what's referred to as the _well pattern_ is that this can be implemented in a number of ways. The heading can be an H3, H4 or H5. It can include or not include paragraph text and a call-to-action link. I'd have to check Wagtail to see all the customization that is possible but it's not a single thing in terms of implementation. 

As a UI designer I don't think of a well as a specific combination of elements. I think of a gray box with the padding. There is a standard implementation - which is the gray box with the heading, paragraph text, and sometimes a standalone link. But we also use the well organism (o-well) in the form context. For example: https://www.consumerfinance.gov/privacy/records-access/

There are other instances of gray boxes with a different padding that don't appear to use the o-well component. So maybe the o-well component is specifically the gray box with the 30px of padding. From a visual perspective what we really we have 2 types of boxes within our components - Box with 30px of padding, Box with 15px of padding. If we're pulling this out to the most simple pieces.

2023-11-21 12:22 UTC, natalia-fitzgerald commented
@billhimmelsbach @meissadia 

Didn't we decide that these would be called: 

- Well (container)
  - No content, just the box with the fill, border, passing, responsive behavior
- Well (content)
  - Placeholder would be the heading (h3), paragraph, and stand-alone link (list link)
  
Like this?  
![Screenshot 2023-11-21 at 7 17 55 AM](https://github.com/cfpb/design-system-react/assets/77348967/f1da4d4d-f031-4f61-b421-d6433ff71985)

This is another example of where we currently use the well in the mock-ups:
- heading (h3), paragraph
 ![Screenshot 2023-11-21 at 7 19 03 AM](https://github.com/cfpb/design-system-react/assets/77348967/552ae190-d788-45f2-8478-8d84fae10d98)
 
 Is there a specific place that we imagine that we will want to use the Well (container) or is that a nice to have in case it's useful for another component we are composing?

2023-11-21 21:23 UTC, billhimmelsbach commented
So to sum up the changes to get this PR approved @meissadia:
- change the titles of the stories to Well (container) and Well (content)
- remove the content from the Well (container)
- change h2 to h3 in Well (content) example

2023-11-21 23:06 UTC, meissadia commented
Updated to address feedback.  Screenshot in PR description has been updated. Tests updated.

2023-11-22 20:53 UTC, billhimmelsbach approved these changes
Looks good! 👍

2023-11-22 20:54 UTC, merged